Controllers/CategoryController.cs
using Sales.Interface;
using Sales.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Sales.Controllers
{
    public class CategoryController : Controller
    {
        public IReposCategory _ReposCategory { get; }

        public CategoryController(IReposCategory ReposCategory)
        {
            this._ReposCategory = ReposCategory;
            
        }
        public ActionResult Index()
        {
           
            return View(_ReposCategory.GetALL());
        }

        public ActionResult Create()
        {
            var category = new Category();

            return View("Create_Edit", category);
        }



        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            // var category = _context.Categories.Find(id);
            var category = _ReposCategory.Search(id);

            if (category == null)
                return HttpNotFound();


            var vModel = new Category
            {
                Name = category.Name,
                Description = category.Description

            };


            return View("Create_Edit", category);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Category models)
        {

            if (!ModelState.IsValid)
                return View("Create_Edit");


            if (models.CategoryId == 0)
            {
                _ReposCategory.Add(models);
                //_context.Categories.Add(models);
            }
            else
            {
                // var category = _context.Categories.Find(models.CategoryId);

                var category = _ReposCategory.Search(models.CategoryId);
                if (category == null)
                {
                    return HttpNotFound();
                }
                category.Name = models.Name;
                category.Description = models.Description;
            }

            _ReposCategory.Save();
            TempData["Message"] = "Saved Successfully";
            return RedirectToAction("Index"); ;
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            //   var customer = _context.Customers.Find(id);
            var customer = _ReposCategory.Search(id);

            if (customer == null)
                return HttpNotFound();

            _ReposCategory.Delete(id);
            //_context.Customers.Remove(customer);
            //_context.SaveChanges();

            TempData["Message"] = "Saved Successfully";
            return RedirectToAction("Index"); ;
        }
    }
}

Controllers/CustomerController.cs
using Sales.Interface;
using Sales.Models;
using Sales.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.NetworkInformation;
using System.Security.Policy;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Xml.Linq;
using Sales.Resources;

namespace Sales.Controllers
{
    public class CustomerController : Controller
    {

        public IReposCustomer _ReposCustomer { get; }

        public CustomerController(IReposCustomer reposCustomer )
        {
            _ReposCustomer = reposCustomer;
        }
        // GET: Customer
        public ActionResult Index()
        {
           
            return View(_ReposCustomer.GetALL());
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            //  var customers = _context.Customers.Find(id);
            var customers = _ReposCustomer.Search(id);
            if (customers == null)
                return HttpNotFound();


            var cVM = new CustomerViewModel
            {
                CustomerID= customers.CustomerID,
                FirstName = customers.FirstName,
                LastName = customers.LastName,
                Email = customers.Email,
                Address = customers.Address,
                Phone = customers.Phone,
                Gender = customers.Gender,

                GenderOptions = new List<SelectListItem>
             {
             // الخيار الأول فارغ
            new SelectListItem { Value = "0", Text = "أنثى" },
            new SelectListItem { Value = "1", Text = "ذكر" }
             }
            };


            return View("Create_Edit", cVM);
        }

        public ActionResult Create()
        {
            var model = new CustomerViewModel
            {
                GenderOptions = new List<SelectListItem>
             {
           
            new SelectListItem { Value = "0", Text = "أنثى" },
            new SelectListItem { Value = "1", Text = "ذكر" }
             }
            };

            return View("Create_Edit",model);
        }

       

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Save(CustomerViewModel viewModels)
        {
            if (!string.IsNullOrEmpty(viewModels.Phone) && !int.TryParse(viewModels.Phone, out _))
            {
                ModelState.AddModelError("Phone", "يرجى إدخال أرقام فقط.");
            }
            if (!ModelState.IsValid)
            {
                
                viewModels.GenderOptions = new List<SelectListItem>
             {
          
            new SelectListItem { Value = "0", Text = "أنثى" },
            new SelectListItem { Value = "1", Text = "ذكر" }
             };
                return View("Create_Edit", viewModels);
                //return View("Create_Edit");

            }

            if (viewModels.CustomerID == 0)
            {
                var customer = new Customer
                {
                    FirstName = viewModels.FirstName,
                    LastName = viewModels.LastName,
                    Email = viewModels.Email,
                    Address = viewModels.Address,
                    Phone = viewModels.Phone,
                    Gender = viewModels.Gender
                };
                _ReposCustomer.Add(customer);
               // _context.Customers.Add(customer);
            }
            else
            {
                var customer = _ReposCustomer.Search(viewModels.CustomerID);
                if (customer == null)
                {
                    return HttpNotFound();
                }
                customer.FirstName = viewModels.FirstName;
                customer.LastName = viewModels.LastName;
                customer.Email = viewModels.Email;
                customer.Address = viewModels.Address;
                customer.Phone = viewModels.Phone;
                customer.Gender = viewModels.Gender;

            }

            _ReposCustomer.Save();
            //_context.SaveChanges();


            TempData["Message"] = "Saved Successfully";
            return RedirectToAction("Index"); 
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            //   var customer = _context.Customers.Find(id);
            var customer = _ReposCustomer.Search(id);

            if (customer == null)
                return HttpNotFound();

            _ReposCustomer.Delete(id);
            //_context.Customers.Remove(customer);
            //_context.SaveChanges();

            TempData["Message"] = "Saved Successfully";
            return RedirectToAction("Index"); ;
        }


    }
}

Controllers/InvoiceController.cs
using Sales.Interface;
using Sales.Models;
using Sales.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sales.Controllers
{
    public class InvoiceController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IReposInvoice _InvoiceRepos;

        public InvoiceController( IReposInvoice InvoiceRepos)
        {
          
            _InvoiceRepos = InvoiceRepos;
            _context = new AppDbContext();
        }
        // GET: Invoice
        public ActionResult Index()
        {
  
            return View(_InvoiceRepos.GetALL());
        }
        public ActionResult Create()
        {
            var model = new InvoiceViewModel
            {
                Customers = _context.Customers.ToList().Select(c => new SelectListItem
                {
                    Value = c.CustomerID.ToString(),
                    Text = $"{c.FirstName} {c.LastName}"
                }),
                Products = _context.Products.ToList().Select(p => new SelectListItem
                {
                    Value = p.ProductId.ToString(),
                    Text = p.FullName
                })
            };

            return View(model);
        }

        // POST: Invoices/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(InvoiceViewModel model)
        {
            if (model.InvoiceDetails.Count == 0)
            {
                ModelState.AddModelError("", "يجب إضافة صنف واحد على الأقل.");
               /* return View(model)*/; // أعد تحميل الصفحة مع الرسالة
            }


            if (ModelState.IsValid)
            {

                var invoice = new Invoice
                {
                    InvoiceDate = DateTime.Now,
                    CustomerId = model.SelectedCustomerId,
                    InvoiceDiscount = model.InvoiceDiscount,
                    InvoiceDetails = model.InvoiceDetails.Select(d => new InvoiceDetail
                    {
                        ProductId = d.ProductId,
                        Quantity = d.Quantity,
                        UnitPrice = d.UnitPrice,
                        Discount = d.Discount
                    }).ToList()
                };
                _InvoiceRepos.Add(invoice);
                _InvoiceRepos.Save();
                //_context.Invoices.Add(invoice);
                //_context.SaveChanges();

                return RedirectToAction("Index");
            }

            // إعادة تحميل بيانات العملاء والمنتجات إذا لم يكن النموذج صالحًا
            model.Customers = _context.Customers.ToList().Select(c => new SelectListItem
            {
                Value = c.CustomerID.ToString(),
                Text = $"{c.FirstName} {c.LastName}"
            });

            model.Products = _context.Products.ToList().Select(p => new SelectListItem
            {
                Value = p.ProductId.ToString(),
                Text = p.FullName
            });

            return View(model);
        }


        // GET: Invoices/GetProductPrice
        public JsonResult GetProductPrice(int productId)
        {
            var product = _context.Products.Find(productId);
            if (product != null)
            {
                return Json(new { price = product.Price }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { price = 0 }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Details(int? id)
        {


            var invoice1 = _InvoiceRepos.Search(id);
            var custmer1 = _context.Customers.Find(invoice1.CustomerId);
            List<InvoiceDetail> iv_details1 = (_context.InvoiceDetails.ToList().
                Where(m => m.InvoiceId == invoice1.InvoiceId)).ToList();


            var VMode = new ViewModelDetails
            {
                invoice = invoice1,

                CustomerId = custmer1.CustomerID,

                customer = custmer1,

                CustomerName = custmer1.FirstName +" "+custmer1.LastName,

                InvoiceDetail0 = iv_details1,

                InvoiceDiscount0 = invoice1.InvoiceDiscount
            };

            return View(VMode);

        }


    }



}

Controllers/ProductController.cs
using Sales.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Sales.ViewModels;
using System.Net;
using Sales.Interface;

namespace Sales.Controllers
{
    public class ProductController : Controller
    {
     
        private readonly IReposProduct _ProductRepos;

        private readonly AppDbContext _context;

        public ProductController(IReposProduct ProductRepos)
        {
            _ProductRepos = ProductRepos;
            _context = new AppDbContext();
        }

        public ActionResult Index()
        {
            return View(_ProductRepos.GetALL());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);


            var products = _ProductRepos.Details(id);
            if (products == null)
                return HttpNotFound();


            return View(products);

        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

           
            var products = _ProductRepos.Search(id);
            
            if (products == null)
                return HttpNotFound();

            var vModel = new ProductViewModels
            {
                ProductId = products.ProductId,
                FullName = products.FullName,
                Price = products.Price,
                CategoryId = products.CategoryId,
                Categories = _context.Categories.ToList()
            };


            return View("Add_Edit", vModel);
        }

        public ActionResult Create()
        {
            var ViewModelProduct = new ProductViewModels
            {
                Categories = _context.Categories.ToList()
            };

            return View("Add_Edit", ViewModelProduct);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Save(ProductViewModels viewModels)
        {
            if (!ModelState.IsValid)
            {
                viewModels.Categories = _context.Categories.ToList();
                return View("Add_Edit");

            }

            if (viewModels.ProductId == 0)
            {
                var product = new Product
                {
                    FullName = viewModels.FullName,
                    Price = viewModels.Price,
                    CategoryId = viewModels.CategoryId
                };
              
                _ProductRepos.Add(product);
            }
            else
            {
                var product = _ProductRepos.Search(viewModels.ProductId);
                if (product == null)
                {
                    return HttpNotFound();
                }
                product.FullName = viewModels.FullName;
                product.Price = viewModels.Price;
                product.CategoryId = viewModels.CategoryId;

            }

            _ProductRepos.Save();
      

            TempData["Message"] = "Saved Successfully";
            return RedirectToAction("Index"); ;
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

          
            var customer = _ProductRepos.Search(id);

            if (customer == null)
                return HttpNotFound();

            _ProductRepos.Delete(id);
         

            TempData["Message"] = "Saved Successfully";
            return RedirectToAction("Index"); ;
        }


    }
}

Views/Shared/_Layout.cshtml
@using System.Web.Mvc
@using System.Web.Optimization
@using System.Web.Routing
@using Sales.Resources


<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @Resource.Salse</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />

    <style>
        .navbar-nav {
            flex-direction: row; /* عرض الأفقي */
        }

            .navbar-nav .nav-link {
                color: #ffffff; /* لون النص أبيض */
            }

                /* تغيير لون النص عند الضغط عليه */
                .navbar-nav .nav-link:focus,
                .navbar-nav .nav-link:hover {
                    color: black; /* النص يصبح أسود عند الضغط */
                    background-color: rgba(255, 255, 255, 0.1); /* إضافة خلفية خفيفة */
                }

        /* لعرض الأيقونات في شكل قائمة على الهواتف */
        media (max-width: 767.98px) {
            .navbar-nav

        {
            flex-direction: column; /* تغيير إلى عمودي */
        }

        .invoice-item {
            order: -1 !important; /* جعل عنصر الفاتورة أولاً */
        }

        .navbar-nav .nav-item {
            order: 0 !important; /* تأكد من أن جميع العناصر الأخرى تأخذ ترتيبًا عاديًا */
        }
        }
    </style>

    @RenderSection("Styles", required: false)
    @Styles.Render("~/Content/css")
</head>

<body>
  
    <nav class="navbar navbar-expand-lg bg-primary">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Home")">
                        <i class="fas fa-home"></i> @Resource.Home
                    </a>
                </li>
                <li class="nav-item invoice-item">
                    <a class="nav-link" href="@Url.Action("Index", "Invoice")">
                        <i class="fas fa-file-invoice"></i> @Resource.Invoice
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Product")">
                        <i class="fas fa-box"></i> @Resource.Products
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Category")">
                        <i class="fas fa-tags"></i> @Resource.Categories
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Customer")">
                        <i class="fas fa-users"></i> @Resource.Customers
                    </a>
                </li>
                @if (Session["Username"] != null)
                {
                    <li class="nav-item" style="margin-left: 430px;">
                        <a class="nav-link" href="@Url.Action("Logout", "User")">
                            <i class="fas fa-sign-out-alt"></i> @Resource.LogOut
                        </a>
                    </li>
                }
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @Resource.Salse</p>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script>
        let timeout;

        function startTimer() {
            timeout = setTimeout(function() {
                if (confirm('@Resource.confirm')) {
                    resetTimer();
                } else {
                    window.location.href = '@Url.Action("Logout", "User")';
                }
            }, 20000); // 120000 مللي ثانية = دقيقتين
        }

        function resetTimer() {
            clearTimeout(timeout);
            startTimer();
        }

        // بدء المؤقت عند تحميل الصفحة
        window.onload = function() {
            startTimer();

            // إعادة تعيين العداد عند تفاعل المستخدم
            document.onmousemove = resetTimer;
            document.onkeypress = resetTimer;
        };
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>